package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func cmdInstall(){pkgPath:="package.json";if len(os.Args)>2{pkgPath=os.Args[2]};pkg,err:=readPackageJSON(pkgPath);if err!=nil{fmt.Fprintf(os.Stderr,"Erreur: %v\n",err);os.Exit(1)};deps:=mergeDeps(pkg);if len(deps)==0{fmt.Println("Aucune dépendance trouvée dans package.json");return};nodeModules:=filepath.Join(filepath.Dir(pkgPath),"node_modules");resetCacheSeen();fmt.Printf("Installation de %d dépendances depuis le cache...\n",len(deps));errors:=installAll(deps,nodeModules);resolved:=make(map[string]string);for name:=range deps{if v:=readInstalledVersion(nodeModules,name);v!=""{resolved[name]=v}};if err:=updateResolvedPackageJSON(pkgPath,resolved);err!=nil{fmt.Fprintf(os.Stderr,"ATTENTION: package.json non mis à jour: %v\n",err)}else if len(resolved)>0{fmt.Printf("package.json mis à jour avec %d versions réellement installées\n",len(resolved))};if errors>0{fmt.Printf("\n%d erreur(s) rencontrée(s)\n",errors)}else{fmt.Println("\nInstallation terminée avec succès !")}}
func installAll(deps map[string]string,nodeModulesDir string)int{type result struct{name string;err error};results:=make(chan result,len(deps));for n,v:=range deps{n,v:=n,v;go func(){results<-result{n,installPackage(n,v,nodeModulesDir)}}()};errors:=0;for range deps{r:=<-results;if r.err!=nil{fmt.Fprintf(os.Stderr,"  ÉCHEC %s: %v\n",r.name,r.err);errors++}};return errors}
func installPackage(name,version,nodeModulesDir string)error{dest:=filepath.Join(nodeModulesDir,name);cached,err:=findCachedVersions(name);if err!=nil||len(cached)==0{return fmt.Errorf("%s n'est pas dans le cache. Lance d'abord 'offpack cache'",name)};resolved:=resolveVersionFromCache(cached,version);if resolved==""{return fmt.Errorf("aucune version de %s satisfaisant %s dans le cache",name,version)};tarball,_:=cachedTarballPath(name,resolved);if err=os.RemoveAll(dest);err!=nil{return err};if err=extractTarball(tarball,dest);err!=nil{return fmt.Errorf("erreur d'extraction de %s: %w",name,err)};manifest,err:=loadCacheManifest(name,resolved);if err==nil&&len(manifest.Dependencies)>0{if n:=installAll(manifest.Dependencies,filepath.Join(dest,"node_modules"));n>0{return fmt.Errorf("%d sous-dépendance(s) échouée(s)",n)}};fmt.Printf("  OK %s@%s\n",name,resolved);return nil}
func resolveVersionFromCache(v []string,c string)string{if c=="latest"||c==""{return findLatestVersion(v)};for _,x:=range v{if x==c{return x}};return resolveBestVersion(v,c)}
func findCachedVersions(name string)([]string,error){cd,e:=cacheDir();if e!=nil{return nil,e};entries,e:=os.ReadDir(filepath.Join(cd,sanitizeName(name)));if e!=nil{return nil,e};var versions []string;for _,x:=range entries{if x.IsDir(){if _,ok:=parseSemver(x.Name());ok{versions=append(versions,x.Name())}}};return versions,nil}
