package main

var topPackages = []string{
	"semver", "glob", "minimatch", "chalk", "debug", "supports-color", "has-flag",
	"color-name", "color-convert", "ansi-styles", "ansi-regex", "strip-ansi",
	"ms", "tslib", "commander", "uuid", "lodash", "yargs", "rimraf", "mkdirp",
	"fs-extra", "cross-spawn", "resolve", "resolve-from", "micromatch",
	"fill-range", "braces", "picomatch", "to-regex-range", "is-number",
	"graceful-fs", "inherits", "util-deprecate", "once", "wrappy", "inflight",
	"minipass", "brace-expansion", "balanced-match", "concat-map",
	"safe-buffer", "readable-stream", "string_decoder", "isarray",
	"source-map", "source-map-js", "escalade", "get-caller-file",
	"require-directory", "y18n", "yargs-parser", "json5", "ajv",
	"json-schema-traverse", "uri-js", "punycode", "fast-deep-equal",
	"fast-json-stable-stringify", "asap", "whatwg-url", "tr46", "webidl-conversions",
	"node-fetch", "axios", "form-data", "combined-stream", "mime-types", "mime-db",
	"asynckit", "delayed-stream", "follow-redirects", "proxy-from-env",
	"qs", "content-type", "accepts", "negotiator", "type-is", "bytes",
	"raw-body", "iconv-lite", "safer-buffer", "depd", "http-errors",
	"setprototypeof", "statuses", "toidentifier", "on-finished", "ee-first",
	"escape-html", "encodeurl", "parseurl", "fresh", "etag", "cookie",
	"cookie-signature", "merge-descriptors", "methods", "finalhandler",
	"send", "range-parser", "mime", "destroy", "vary", "proxy-addr",
	"ipaddr.js", "array-flatten", "path-to-regexp", "body-parser",
	"express", "cors", "helmet", "morgan", "compression", "serve-static",
	"jsonwebtoken", "bcryptjs", "passport", "passport-local",
	"mongoose", "mongodb", "bson", "mongodb-connection-string-url",
	"@mongodb-js/saslprep", "memory-pager", "sparse-bitfield",
	"kareem", "mpath", "mquery", "sift", "regexp-clone", "mongodb-client-encryption",
	"prisma", "@prisma/client", "@prisma/engines",
	"sequelize", "pg", "pg-types", "pgpass", "pg-connection-string",
	"pg-int8", "postgres-array", "postgres-bytea", "postgres-date",
	"postgres-interval", "xtend", "packet-reader",
	"mysql2", "mysql", "sqlstring", "denque", "generate-function",
	"@types/node", "@types/react", "@types/express", "@types/lodash",
	"typescript", "ts-node", "tsx", "esbuild",
	"react", "react-dom", "react-is", "react-router", "react-router-dom",
	"react-hook-form", "react-query", "@tanstack/react-query",
	"react-redux", "redux", "redux-thunk", "immer", "reselect",
	"next", "@next/env", "@next/swc-linux-x64-gnu",
	"vue", "vue-router", "pinia", "vuex",
	"@angular/core", "@angular/common", "@angular/compiler",
	"@angular/platform-browser", "@angular/forms", "@angular/router",
	"rxjs", "zone.js", "tslib",
	"svelte", "@sveltejs/kit",
	"vite", "@vitejs/plugin-react", "@vitejs/plugin-vue",
	"rollup", "@rollup/rollup-linux-x64-gnu", "esbuild",
	"webpack", "webpack-dev-server", "webpack-cli", "webpack-merge",
	"@webpack-cli/serve", "enhanced-resolve", "watchpack", "tapable",
	"schema-utils", "ajv-formats", "json-parse-even-better-errors",
	"browserslist", "caniuse-lite", "electron-to-chromium",
	"eslint", "@eslint/js", "eslint-scope", "eslint-visitor-keys",
	"espree", "acorn", "acorn-jsx", "estraverse", "esutils",
	"prettier", "@prettier/plugin-xml",
	"postcss", "autoprefixer", "cssnano", "css-declaration-sorter",
	"postcss-calc", "postcss-colormin", "postcss-convert-values",
	"postcss-discard-comments", "postcss-discard-duplicates",
	"postcss-discard-empty", "postcss-discard-overridden",
	"postcss-merge-longhand", "postcss-merge-rules",
	"postcss-minify-font-values", "postcss-minify-gradients",
	"postcss-minify-params", "postcss-minify-selectors",
	"postcss-normalize-charset", "postcss-normalize-display-values",
	"postcss-normalize-positions", "postcss-normalize-repeat-style",
	"postcss-normalize-string", "postcss-normalize-timing-functions",
	"postcss-normalize-unicode", "postcss-normalize-url",
	"postcss-normalize-whitespace", "postcss-ordered-values",
	"postcss-reduce-initial", "postcss-reduce-transforms",
	"postcss-svgo", "postcss-unique-selectors", "stylehacks",
	"css-select", "css-tree", "css-what", "csso", "dom-serializer",
	"domelementtype", "domhandler", "domutils", "entities", "nth-check",
	"svgo", "stable", "coa", "q",
	"sass", "sass-loader", "node-sass", "less", "less-loader",
	"tailwindcss", "postcss-import", "postcss-nesting",
	"bootstrap", "bootstrap-icons", "jquery", "popperjs",
	"@babel/core", "@babel/parser", "@babel/traverse", "@babel/generator",
	"@babel/types", "@babel/template", "@babel/code-frame",
	"@babel/helper-validator-identifier", "@babel/helper-string-parser",
	"@babel/helper-module-imports", "@babel/helper-module-transforms",
	"@babel/helper-simple-access", "@babel/helper-split-export-declaration",
	"@babel/helpers", "@babel/runtime", "@babel/plugin-transform-runtime",
	"@babel/preset-env", "@babel/preset-react", "@babel/preset-typescript",
	"@babel/compat-data", "regenerator-runtime", "regenerator-transform",
	"@babel/plugin-transform-arrow-functions",
	"@babel/plugin-transform-block-scoping",
	"@babel/plugin-transform-classes", "@babel/plugin-transform-computed-properties",
	"@babel/plugin-transform-destructuring",
	"@babel/plugin-transform-for-of", "@babel/plugin-transform-function-name",
	"@babel/plugin-transform-literals", "@babel/plugin-transform-modules-commonjs",
	"@babel/plugin-transform-object-super",
	"@babel/plugin-transform-parameters",
	"@babel/plugin-transform-shorthand-properties",
	"@babel/plugin-transform-spread",
	"@babel/plugin-transform-sticky-regex",
	"@babel/plugin-transform-template-literals",
	"@babel/plugin-transform-typeof-symbol",
	"@babel/plugin-transform-unicode-regex",
	"@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining",
	"@babel/plugin-proposal-unicode-property-regex",
	"@babel/plugin-syntax-async-generators", "@babel/plugin-syntax-class-properties",
	"@babel/plugin-syntax-dynamic-import", "@babel/plugin-syntax-import-meta",
	"@babel/plugin-syntax-json-strings", "@babel/plugin-syntax-jsx",
	"@babel/plugin-syntax-nullish-coalescing-operator",
	"@babel/plugin-syntax-numeric-separator",
	"@babel/plugin-syntax-object-rest-spread",
	"@babel/plugin-syntax-optional-catch-binding",
	"@babel/plugin-syntax-optional-chaining",
	"@babel/plugin-syntax-top-level-await",
	"babel-loader", "ts-loader", "style-loader", "css-loader",
	"postcss-loader", "html-webpack-plugin", "mini-css-extract-plugin",
	"terser-webpack-plugin", "css-minimizer-webpack-plugin",
	"swc-loader", "@swc/core", "@swc/counter", "@swc/types",
	"zod", "yup", "joi", "validator",
	"date-fns", "dayjs", "moment", "luxon",
	"dotenv", "cross-env", "envinfo",
	"chokidar", "anymatch", "normalize-path", "glob-parent", "binary-extensions",
	"readdirp", "fsevents",
	"nodemon", "pstree.remy", "touch", "nopt", "abbrev",
	"body-parser", "multer", "busboy", "streamsearch",
	"cors", "helmet", "compression", "serve-favicon",
	"bcrypt", "bcryptjs", "crypto-js", "argon2", "speakeasy",
	"passport", "passport-jwt", "passport-google-oauth20",
	"jsonwebtoken", "json2csv", "csv-parse", "csv-stringify",
	"multer", "sharp", "jimp", "pngjs",
	"nodemailer", "nodemailer-smtp-transport",
	"socket.io", "socket.io-client", "engine.io", "engine.io-client",
	"ws", "websocket", "websocket-driver", "websocket-extensions",
	"http-proxy", "http-proxy-middleware",
	"redis", "ioredis", "cluster-key-slot",
	"ioredis", "@redis/client", "@redis/bloom",
	"cron", "node-cron", "node-schedule",
	"pino", "winston", "log4js", "bunyan", "signale",
	"winston-transport", "logform", "triple-beam", "stack-trace",
	"colors", "cli-color", "picocolors",
	"ora", "cli-spinners", "log-symbols", "restore-cursor",
	"figures", "is-unicode-supported",
	"listr2", "colorette",
	"inquirer", "@inquirer/prompts", "@inquirer/input",
	"execa", "human-signals", "npm-run-path", "is-stream", "strip-final-newline",
	"signal-exit", "onetime", "mimic-fn",
	"which", "isexe",
	"find-up", "locate-path", "p-locate", "p-limit", "yocto-queue",
	"path-exists", "pkg-dir",
	"cosmiconfig", "import-fresh", "parent-module", "callsites",
	"@jridgewell/trace-mapping", "@jridgewell/sourcemap-codec",
	"@jridgewell/resolve-uri", "@jridgewell/gen-mapping",
	"@jridgewell/set-array", "jsesc",
	"regenerator-runtime", "regenerator-transform", "private",
	"object-assign", "prop-types", "loose-envify", "js-tokens",
	"react-refresh", "scheduler",
	"@emotion/react", "@emotion/styled", "@emotion/cache",
	"@emotion/serialize", "@emotion/utils", "@emotion/weak-memoize",
	"@emotion/memoize", "@emotion/hash", "@emotion/unitless",
	"styled-components", "stylis", "shallowequal",
	"ethers", "web3", "@solana/web3.js",
	"graphql", "@graphql-tools/schema", "graphql-yoga", "apollo-server",
	"@apollo/client", "graphql-tag", "graphql-ws",
	"openai", "@anthropic-ai/sdk", "@huggingface/inference",
	"langchain", "@langchain/core",
	"hono", "itty-router", "worktop",
	"fastify", "fast-json-stringify", "fastify-plugin", "light-my-request",
	"@fastify/ajv-compiler", "find-my-way", "secure-json-parse",
	"@fastify/error", "avvio", "reusify",
	"koa", "koa-router", "koa-bodyparser", "koa-compose",
	"co", "delegates", "only", "koa-convert",
	"nest", "@nestjs/core", "@nestjs/common", "@nestjs/platform-express",
	"@nuxt/core", "@nuxt/kit", "nuxt", "nitropack", "h3", "ofetch",
	"cheerio", "jsdom", "htmlparser2", "parse5",
	"puppeteer", "playwright",
	"zod", "@zod/mini", "valibot", "arktype",
	"zod", "trpc", "@trpc/client", "@trpc/server", "@trpc/react-query",
	"zustand", "jotai", "valtio", "recoil",
	"swr", "use-sync-external-store",
	"framer-motion", "popmotion", "framesync", "hey-listen",
	"@testing-library/react", "@testing-library/jest-dom",
	"@testing-library/user-event", "@testing-library/dom",
	"vitest", "@vitest/runner", "@vitest/snapshot",
	"jest", "@jest/core", "@jest/types", "jest-worker", "jest-util",
	"jest-environment-node", "jest-haste-map", "jest-message-util",
	"jest-mock", "jest-regex-util", "jest-resolve",
	"jest-runtime", "jest-snapshot",
	"pretty-format", "@sinclair/typebox", "diff-sequences",
	"@sinonjs/fake-timers", "@sinonjs/commons",
	"stack-utils", "picocolors",
	"mocha", "chai", "assertion-error", "should", "expect",
	"nock", "sinon", "sinon-chai",
	"cypress", "@cypress/request", "@cypress/xvfb",
	"@playwright/test", "playwright-core",
	"oclif", "@oclif/core", "cli-progress", "cli-ux",
	"commander", "yargs", "meow", "arg", "nopt",
	"conf", "env-paths", "atomically",
	"update-notifier", "boxen", "widest-line", "camelcase",
	"configstore", "xdg-basedir", "unique-string", "crypto-random-string",
	"got", "ky", "undici", "node-fetch-native", "ofetch",
	"axios", "superagent", "needle",
	"path-browserify", "process", "buffer", "events", "stream-browserify",
	"util", "assert", "url", "querystring-es3",
	"crypto-browserify", "browserify-zlib", "constants-browserify",
	"vm-browserify", "os-browserify", "https-browserify",
	"http-browserify", "timers-browserify", "tty-browserify",
	"@aws-sdk/client-s3", "@aws-sdk/client-lambda",
	"@aws-sdk/client-dynamodb", "@aws-sdk/client-sqs",
	"@aws-sdk/client-sns", "@aws-sdk/lib-dynamodb",
	"@aws-sdk/types", "@aws-sdk/util-utf8", "@aws-sdk/middleware-stack",
	"@smithy/types", "@smithy/util-utf8", "@smithy/middleware-stack",
	"@google-cloud/storage", "@google-cloud/pubsub",
	"firebase", "firebase-admin", "@firebase/app",
	"@azure/storage-blob", "@azure/identity",
	"stripe", "@stripe/stripe-js",
	"swagger-ui-express", "swagger-jsdoc",
	"class-validator", "class-transformer", "reflect-metadata",
	"rxjs", "reflect-metadata",
	"bull", "bullmq", "ioredis", "bee-queue",
	"amqplib", "amqp-connection-manager",
	"kafka-node", "kafkajs", "@confluentinc/kafka-javascript",
	"pm2", "pm2-axon", "pm2-axon-rpc", "pm2-deploy", "pm2-multimeter",
	"forever", "nssocket", "lazy", "cliff", "broadway", "utile",
	"helmet", "csurf", "cookie-parser", "express-session",
	"express-rate-limit", "express-validator",
	"connect-redis", "session-file-store",
	"memorystore", "cache-manager", "node-cache",
	"memoizee", "es5-ext", "es6-iterator", "ext",
	"lru-cache", "mnemonist", "obliterator",
	"async", "neo-async", "queue-microtask", "fastq",
	"p-map", "p-all", "p-filter", "p-retry", "p-queue",
	"p-throttle", "p-limit", "p-cancelable", "p-timeout",
	"delay", "p-wait-for", "p-whilst",
	"nanoid", "nanoid", "uid2", "uid-safe", "random-bytes",
	"bcryptjs", "bcrypt", "argon2", "pbkdf2",
	"crypto-random-string", "unique-string",
	"ip", "ipaddr.js", "cidr-regex", "is-cidr",
	"tldts", "psl", "cookie", "tough-cookie",
	"html-entities", "he", "entities",
	"marked", "remarkable", "markdown-it", "mdurl", "uc.micro",
	"highlight.js", "lowlight", "fault", "hastscript", "property-information",
	"space-separated-tokens", "comma-separated-tokens", "hast-util-parse-selector",
	"rehype", "remark", "unified", "vfile", "bail", "trough",
	"unist-util-stringify-position", "unist-util-visit",
	"graceful-fs", "jsonfile", "universalify",
	"@nodelib/fs.stat", "@nodelib/fs.walk", "@nodelib/fs.scandir",
	"fast-glob", "merge2", "run-parallel",
	"slash", "normalize-path", "path-type",
	"globby", "ignore", "dir-glob",
	"is-glob", "is-extglob", "is-docker", "is-wsl",
	"is-ci", "ci-info",
	"is-plain-object", "isobject",
	"deepmerge", "merge-deep", "clone-deep",
	"clone", "clone-response", "decompress-response",
	"mimic-response", "responselike",
	"camelcase", "decamelize", "humanize-string",
	"pluralize", "inflected",
	"escape-string-regexp", "pkg-up",
	"regexp-tree", "safe-regex",
	"semver", "semver-diff", "semver-regex",
	"@sindresorhus/is", "is-unicorn",
	"env-paths", "temp-dir", "tempy",
	"is-path-inside", "is-path-cwd",
	"del", "p-map", "aggregate-error", "clean-stack",
	"make-dir", "pify",
	"read-pkg", "read-pkg-up", "type-fest",
	"normalize-url", "prepend-http", "query-string",
	"split-on-first", "decode-uri-component", "filter-obj",
	"strict-uri-encode", "sort-keys", "is-plain-obj",
	"arrify", "multimap", "map-obj",
	"quick-lru", "yoctocolors",
	"@szmarczak/http-timer", "cacheable-lookup", "cacheable-request",
	"keyv", "compress-brotli",
	"http-cache-semantics", "lowercase-keys", "p-cancelable",
	"responselike",
	"@tokenizer/token", "strtok3", "peek-readable", "token-types",
	"file-type", "strtok3",
	"is-binary-path", "binary-extensions",
	"undici-types", "busboy",
	"dockerode", "docker-modem", "tar-fs", "tar-stream",
	"tar", "minipass", "minizlib", "node-gyp",
	"make-fetch-happen", "negotiator", "promise-retry",
	"retry", "err-code", "ip-address", "jsbn",
	"ssri", "unique-filename", "unique-slug", "imurmurhash",
	"cacache", "pacote", "npm-pick-manifest",
	"npm-registry-fetch", "npm-package-arg", "hosted-git-info",
	"validate-npm-package-name", "normalize-package-data",
	"get-stream", "pump", "end-of-stream",
	"bl", "buffer", "ieee754", "base64-js",
	"through2", "through", "pumpify", "duplexify", "stream-shift",
	"split2", "binary-split",
	"module-details-from-path", "require-in-the-middle",
	"async-hook-jl", "emitter-listener", "shimmer",
	"@opentelemetry/api", "@opentelemetry/sdk-trace-base",
	"@opentelemetry/core", "@opentelemetry/resources",
	"@opentelemetry/semantic-conventions",
	"@opentelemetry/instrumentation",
	"require-in-the-middle", "import-in-the-middle",
	"cjs-module-lexer", "module-details-from-path",
	"content-disposition", "content-type",
	"media-typer", "range-parser",
	"@hapi/hoek", "@hapi/topo", "@sideway/address", "@sideway/formula",
	"joi",
	"@sinclair/typebox", "type-fest",
	"tsx", "esno", "bun",
}
